<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { supabase } from '@/supabaseClient'
import { getGiftCapabilities } from '@/utils/giftCapabilities'
const route = useRoute(); const router = useRouter(); const saving = ref(false); const error = ref(''); const from = ref(''); const to = ref(''); const theme = ref('romance'); const message = ref(''); const memories = ref<string[]>([]); const canUpload = ref(true); const claimValid = ref(false)
onMounted(() => { try { const claim = JSON.parse(localStorage.getItem('stack-petals:letter-v2-claim') || 'null'); claimValid.value = Boolean(claim?.token === String(route.params.token || '') && claim?.qrId); canUpload.value = getGiftCapabilities(claim).hasPhotoUpload } catch { claimValid.value = false } if (!claimValid.value) error.value = 'Open this page from the LetterPage V2 QR link first.' })
function readFile(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(reader.error); reader.readAsDataURL(file) }) }
async function addPhoto(event: Event) { if (!canUpload.value) return; const input = event.target as HTMLInputElement; const files = Array.from(input.files || []).slice(0, 3 - memories.value.length); for (const file of files) memories.value.push(await readFile(file)); input.value = '' }
async function publish() { if (!claimValid.value) return; saving.value = true; error.value = ''; try { const { data, error: rpcError } = await supabase.rpc('create_letter_v2', { p_public_token: String(route.params.token || ''), p_from: from.value.trim(), p_to: to.value.trim(), p_theme: theme.value, p_message: message.value.trim(), p_memories: memories.value }); if (rpcError) throw rpcError; const id = Array.isArray(data) ? data[0]?.id : data?.id; if (!id) throw new Error('The LetterPage V2 letter could not be created.'); localStorage.removeItem('stack-petals:letter-v2-claim'); await router.replace(`/letter-v2/${id}`) } catch (caught) { error.value = caught instanceof Error ? caught.message : 'Could not save the letter.' } finally { saving.value = false } }
</script>
<template><main class="v2-create"><section class="v2-card"><p class="eyebrow">Standalone LetterPage V2</p><h1>Create your letter</h1><p class="intro">This QR belongs exclusively to the LetterPage V2 experience.</p><div class="fields"><label>From<input v-model="from" placeholder="Your name"></label><label>To<input v-model="to" placeholder="Recipient name"></label><label>Theme<select v-model="theme"><option value="romance">Romance</option><option value="family">Family</option><option value="birthday">Birthday</option><option value="sympathy">Sympathy</option><option value="friendship">Friendship</option><option value="graduation">Graduation</option></select></label><label>Your message<textarea v-model="message" rows="8" maxlength="2000" placeholder="Write something from the heart..."></textarea></label><label v-if="canUpload">Memories <span>(up to 3 photos)</span><input type="file" accept="image/*" multiple @change="addPhoto"></label></div><p v-if="error" class="error">{{ error }}</p><button :disabled="saving || !claimValid || !to.trim() || !message.trim()" @click="publish">{{ saving ? 'Publishing…' : 'Publish LetterPage V2' }}</button></section></main></template>
<style scoped>.v2-create{min-height:100vh;display:grid;place-items:center;padding:24px;background:#f8eeee;color:#49343b}.v2-card{width:min(100%,620px);padding:clamp(26px,5vw,48px);border:1px solid #dfbfc1;border-radius:24px;background:#fffdfa;box-shadow:0 20px 70px #6b46521c}.eyebrow{color:#a05d72;font:600 11px 'DM Sans';letter-spacing:.2em;text-transform:uppercase}.v2-card h1{margin:8px 0;font:400 clamp(38px,7vw,58px)/1 'Cormorant Garamond'}.intro{color:#806e73;font:15px 'DM Sans'}.fields{display:grid;gap:16px;margin-top:24px}.fields label{display:grid;gap:7px;color:#74515d;font:600 12px 'DM Sans'}.fields span{font-weight:400;color:#a28c91}input,select,textarea{box-sizing:border-box;width:100%;border:1px solid #dcb8bd;border-radius:10px;padding:12px;background:#fff;color:#49343b;font:15px 'DM Sans'}textarea{resize:vertical}.v2-card button{margin-top:22px;width:100%;border:0;border-radius:999px;padding:14px;background:#5e8d79;color:#fff;font:700 14px 'DM Sans';cursor:pointer}.v2-card button:disabled{opacity:.5}.error{color:#a14f5d;font:14px 'DM Sans'}</style>
